version: "3"
services:
  #  Create a service named db.
  wp-db:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
    #   Give the container the name my_postgres. You can changes to something else.
    container_name: "dians-2022"
    #   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=dians
      - POSTGRES_PASSWORD=dians123
      - POSTGRES_DB=banks
    #   Maps port 5430 (localhost) to port 5430 on the container. You can change the ports to fix your needs.
    ports:
      - "5430:5432"
    #   Set a volume some that database is not lost after shutting down the container.
    #   I used the name postgres-data but you can changed it to something else.
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
