version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dians
      POSTGRES_PASSWORD: dians123
      POSTGRES_DB: banks
  web:
    build: ./spring-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5436/banks
      DATABASE_USERNAME: dians
      DATABASE_PASSWORD: dians123
  frontend:
    build: ./nuxt
    ports:
      - "3000:3000"